##
# Publish HTML to GH Pages
# - Runs the build script.
# - Moves relevant artifacts to publishing directory
# - Moves publishing directory contents to GH pages.
##

name: Test GIT

on:
  push:
    branches:
      - gh-pages-setup-test-2

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: git --version
      - run: git log
      - run: git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d'
